---
# tasks file for helm
- name: Extract Helm
  unarchive:
    src: https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz
    dest: /home/vagrant
    remote_src: yes


- name: Move Helm to /usr/local/bin
  copy:
    src: /home/vagrant/linux-amd64/helm
    dest: /usr/local/bin
    owner: 'vagrant'
    group: 'vagrant'
    mode: 0755
    remote_src: yes

- name: Remove Linux-AMD64-HELM
  file:
    state: absent
    path: /home/vagrant/linux-amd64

- name: 'Change kubeconfig file permission'
  file:
    path: /home/vagrant/.kube
    owner: 'vagrant'
    group: 'vagrant'
    mode: 0774
    recurse: yes


