---
#- import_playbook: ./playbooks/base.yml
#- import_playbook: ./playbooks/master.yml
#- import_playbook: ./playbooks/slave.yml
#- import_playbook: ./playbooks/spark.yml
#- import_playbook: ./playbooks/helm.yml
#- import_playbook: ./playbooks/zabbix-monitoring.yml
- hosts: master_nodes
  become: true
  roles:
    - master
- hosts: worker_nodes
  become: true
  roles:
    - slave
- import_playbook: ./playbooks/spark.yml
- hosts: master_nodes
  become: true
  roles:
    - zabbix-monitoring
