---
- import_playbook: ./playbooks/base.yml
- import_playbook: ./playbooks/master.yml
- import_playbook: ./playbooks/slave.yml
- import_playbook: ./playbooks/spark.yml
- import_playbook: ./playbooks/helm.yml
- import_playbook: ./playbooks/zabbix-monitoring.yml
