apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: apache/spark:latest
        command:
        - /bin/bash
        - -c
        - "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: apache/spark:latest
        command:
        - /bin/bash
        - -c
        - "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master-service:7077"
