---
- hosts: master_nodes
  become: true
  tasks:
  - name: Copy manifests
    copy:
      src: '{{ item }}'
      dest: ./
    with_fileglob:
      - ../spark/*

  - name: Create Spark namespace
    command: kubectl create namespace spark
    become: false

  - name: Apply Spark master service
    command: kubectl apply -f ./spark-master-service.yaml -n spark
    become: false

  - name: Apply Spark deployment
    command: kubectl apply -f ./spark-deployment.yaml -n spark
    become: false